
export enum QuestDifficulty {
  EASY = 'EASY',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD'
}

export enum QuestStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED'
}

export interface Quest {
  id: string;
  title: string;
  description: string; // Generated by Gemini
  difficulty: QuestDifficulty;
  status: QuestStatus;
  rewardXP: number;
  rewardGold: number;
  timestamp: number;
}

export interface PlayerStats {
  hp: number; // Focus/Energy
  maxHp: number;
  mana: number; // Available Hours
  maxMana: number;
  gold: number; // Projects delivered
  xp: number;
  level: number;
}

export interface UserContext {
  name: string;
  role: string;
}

export enum ViewSection {
  DASHBOARD = 'dashboard',
  PROFILE = 'profile',
  ANALYTICS = 'analytics',
  SETTINGS = 'settings',
  SHOP = 'shop',
  ACHIEVEMENTS = 'achievements'
}
